module.exports = function(exports, imports) {
  return imports(function
    ( run
    , route
    , html
    , node$listen
    , app$static
    ) {

    with (html) return run()
      (node$listen, 80)
      (route, /^\/static/)
        (app$static)
      ()
      (DOCTYPE, "html")
      (HTML)
        (HEAD)
          (META, {charset: "utf-8"})
          (TITLE)("(fab) テストアプリ on no.de")()
          (LINK, {rel: "stylesheet", href: "/static/base.css", type: "text/css"})
        ()
        (BODY, { id: "show" })
          (DIV, {id: "header"})
            (A, {href: "/"})("top")()
          ()
          (DIV, {id: "content"})
            (route, /^\/$/)
              (H1)("(fab) テストアプリ on no.de")()
              (UL)
                (LI)(A, {href: "/hello"})("/hello")()()
                (LI)(A, {href: "/hello/foo"})("/hello/foo")()()
                (LI)(A, {href: "/hello/foo/bar"})("/hello/foo/bar")()()
              ()
            ()
            (route, /^\/hello/)
              ("Hello, ")
              (EM)
                (route, /^\/(\w+)\/?$/)
                  (route.capture, 0)
                ()
                (route, /^\/(\w+)\/(\w+)\/?$/)
                  (route.capture, 0)
                  (" ")
                  (route.capture, 1)
                ()
                  ( "world" )
              ()
              ("!")
            ()
              ("404 Page Not found.", {status: 404})
            ()
          ()
          (DIV, {id: "footer"})
            ("&copy; ")(A, {href: "http://twitter.com/nsyee"})("@nsyee")()
          ()
        ()
      ()
    ()
    ()
//   (", {status: 200, headers: {"Content-Type": "text/html; charset=utf-8"}})
  })
}